preprocessing:
  download: True
  image_size: 227
  random_affine:
    degrees: 25
    translate: !!python/tuple [0.1, 0.1]
    scale: !!python/tuple [0.9, 1.1]
    shear: 8

model:
  name: mobilenet3_small
  kwargs:
    scaling_parameter: 1
    n_classes: 196

experiment:
  learning_rate: 0.001
  optimizer: AdamW
  batch_size: 64
  loss_function: cross_entropy

trainer:
  max_epochs: 5
  fast_dev_run: False
  early_stop_callback: True

neptune:
  enabled: true