preprocessing:
  download: True
  image_size: 227
  augmentations:
    random_affine: True
    grayscale: False
    color_jitter: True
    random_erasing: False
    horizontal_flip: True
    random_perspective: False
    random_rotation: False
  augmentation_kwargs:
    random_affine:
      degrees: 20
      translate: !!python/tuple [0.1, 0.1]
      scale: !!python/tuple [0.9, 1.1]
      shear: 8
    grayscale:
      num_output_channels: 1
    color_jitter:
      brightness: 0.25
      contrast: 0.25
      saturation: 0.25
      hue: 0.1
    random_erasing:
      p: 0.5
      scale: [0.02, 0.25]
    horizontal_flip:
      p: 0.5
    random_perspective:
      distortion_scale: 0.25
      p: 0.40
    random_rotation:
      degrees: 25

model:
  name: mobilenet3_small
  kwargs:
    scaling_parameter: 1
    n_classes: 196

experiment:
  early_stop: 20
  optimizer: AdamW
  optimizer_kwargs:
    lr: 0.001
    weight_decay: 0.05
#  scheduler: reduce_on_plateu
#  scheduler_kwargs:
#    factor: 0.1
#    patience: 13
#    threshold: 0.001
#    min_lr: 0.0000001
  scheduler: multi_step
  scheduler_kwargs:
    milestones: [64, 98, 106, 116]
    gamma: 0.1
    last_epoch: -1
  batch_size: 64
  loss_function: label_smoothing_cross_entropy

trainer:
  max_epochs: 150
  fast_dev_run: False

neptune:
  enabled: true