preprocessing:
  download: True
  image_size: 227
  augmentations:
    random_affine: True
    grayscale: False
    color_jitter: True
    random_erasing: False
    horizontal_flip: True
    random_perspective: False
    random_rotation: False
  augmentation_kwargs:
    random_affine:
      degrees: 15
      translate: !!python/tuple [0.1, 0.1]
      scale: !!python/tuple [0.9, 1.1]
      shear: 8
    grayscale:
      num_output_channels: 1
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    random_erasing:
      p: 0.5
      scale: [0.02, 0.25]
    horizontal_flip:
      p: 0.5
    random_perspective:
      distortion_scale: 0.15
      p: 0.40
    random_rotation:
      degrees: 25

model:
  name: mobilenet1
  kwargs:
    scaling_parameter: 1
    n_classes: 196

experiment:
  early_stop: 20
  optimizer: AdamW
  optimizer_kwargs:
    lr: 0.001
#    weight_decay:
#  scheduler: reduce_on_plateu
#  scheduler_kwargs:
#    factor: 0.1
#    patience: 13
#    threshold: 0.001
#    min_lr: 0.0000001

#  scheduler: multi_step
#  scheduler_kwargs:
#    milestones: [60, 80, 90, 100]
#    gamma: 0.1
#    last_epoch: -1

  scheduler: annealing
  scheduler_kwargs:
    T_max: 120
    eta_min: 0.00001

  batch_size: 64
  loss_function: label_smoothin_cross_entropy

trainer:
  max_epochs: 120
  fast_dev_run: False

neptune:
  enabled: true