preprocessing:
  download: True
  image_size: 227
  random_affine:
    degrees: 25
    translate: !!python/tuple [0.1, 0.1]
    scale: !!python/tuple [0.9, 1.1]
    shear: 8
  color_jitter:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.1
  random_erasing:
    p: 0.5
    scale: [0.02, 0.25]

model:
  name: mobilenet2
  kwargs:
    scaling_parameter: 1
    n_classes: 196

experiment:
  optimizer: AdamW
  optimizer_kwargs:
    lr: 0.001
    weight_decay: 0.6
#  scheduler: reduce_on_plateu
#  scheduler_kwargs:
#    factor: 0.1
#    patience: 5
#    threshold: 0.001
#    min_lr: 0.0000001
#  scheduler: multi_step
#  scheduler_kwargs:
#    milestones: [64, 98, 106, 116]
#    gamma: 0.1
#    last_epoch: -1
  batch_size: 64
  loss_function: cross_entropy

trainer:
  max_epochs: 225
  fast_dev_run: False

neptune:
  enabled: true